apiVersion: v1
kind: Service
metadata:
  name: frc2024api
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: frc2024api
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  clusterIP: None
  ports:
  - port: 25060

---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgresql
subsets:
  - addresses:
        - ip: 167.172.120.38
    ports:
      - port: 25060
        name: postgresql